AWSTemplateFormatVersion: '2010-09-09'
Description: ALB TargetGroup Template

Parameters:
  Prefix:
    Type: String
  
  VPCId:
    Type: String
  InstanceId:
    Type: String
  ALBArn:
    Type: String

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join ['-', ['tg', !Ref Prefix]]
      VpcId: !Ref VPCId
      # HealthCheck
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: '/'
      HealthCheckPort: '80'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      # Routing
      #XXX: トラフィックポートの場合は 'traffic-port'
      Port: '80'
      Protocol: HTTP
      TargetType: 'instance'
      TargetGroupAttributes:
        # ターゲットの登録解除までの待機時間
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 300
      # 紐付ける対象インスタンスの指定
      Targets:
        - Id: !Ref InstanceId
          Port: 80

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      # Certificates: !Ref ACMArn
      DefaultActions:
        - Type: 'forward'
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALBArn
      Port: '80'
      Protocol: 'HTTP'
      # http://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/application/create-https-listener.html
      # SslPolicy: 'ELBSecurityPolicy-2016-08'
  
#  ListenerRule:
#    Type: AWS::ElasticLoadBalancingV2::ListenerRule
#    Properties:
#      Actions:
#        - Type: 'forward'
#          TargetGroupArn: !Ref TargetGroup
#      # MEMO:
#      #   リスナーの条件
#      # 参考:
#      #   http://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/APIReference/API_RuleCondition.html
#      Conditions:
#        - Field: 'path-pattern'
#          Values: ['/img/*']
#      ListenerArn: !Ref ALBListener
#      Priority: 10

