AWSTemplateFormatVersion: '2010-09-09'
Description: ALB Template

Parameters:
  Prefix:
    Type: String
  VPCId:
    Type: String
  SubnetPublic1a:
    Type: String
  SubnetPublic1c:
    Type: String

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: 'application'
      Name: !Join ['-', ['alb', !Ref Prefix]]
      IpAddressType: 'ipv4'
      Scheme: 'internet-facing'
      Subnets:
        - !Ref SubnetPublic1a
        - !Ref SubnetPublic1c
      # MEMO:
      #   LoadBalancerAttributesはLBのログの保存・削除保護・アイドルタイムアウトの設定を行う事が可能
      # 参考:
      #   ドキュメント
      #     http://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html
      #     http://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes
      #   アイドルタイムアウトについて(CLB)
      #     http://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/classic/config-idle-timeout.html
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 140
      
